const Reference = {
    Base: {
        White: "#FFFFFF",
        Black: "#000000",
    },
    Primary: {
        3: "#FAFAFF",
        6: "#F1F1FE",
        8: "#E0E0FF",
        10: "#D4D4FB",
        20: "#B7B7F8",
        30: "#A1A1FF",
        40: "#6F6FF1",
        50: "#5D5DCA",
        60: "#4B4BA4",
        70: "#3A3A7D",
        80: "#282857",
        90: "#161630",
    },
    Neutral: {
        3: "#FCFCFD",
        6: "#F9FAFB",
        10: "#F2F4F7",
        20: "#EAECF0",
        30: "#D0D5DD",
        40: "#98A2B3",
        50: "#667085",
        60: "#4B5565",
        70: "#344054",
        75: "#28313E",
        80: "#182230",
        90: "#101828",
        95: "#0B0B0F",
    },
    Red: {
        3: "#FFFBFA",
        6: "#FEF3F2",
        10: "#FEE4E2",
        20: "#FECDCA",
        30: "#FDA29B",
        40: "#F97066",
        50: "#F04438",
        60: "#D92D20",
        70: "#B42318",
        80: "#912018",
        90: "#7A271A",
        95: "#7A271A",
    },
    Yellow: {
        3: "#FFFCF5",
        6: "#FFFAEB",
        10: "#FEF0C7",
        20: "#FEDF89",
        30: "#FEC84B",
        40: "#FDB022",
        50: "#F79009",
        60: "#DC6803",
        70: "#B54708",
        80: "#93370D",
        90: "#7A2E0E",
        95: "#4E1D09"
    },
    Green: {
        3: "#F6FEF9",
        6: "#ECFDF3",
        10: "#DCFAE6",
        20: "#ABEFC6",
        30: "#75E0A7",
        40: "#47CD89",
        50: "#17B26A",
        60: "#079455",
        70: "#067647",
        80: "#085D3A",
        90: "#074D31",
        95: "#053321"
    },
    Blue: {
        3: "#F5FAFF",
        6: "#EFF8FF",
        10: "#D2E9FF",
        20: "#B2DDFF",
        30: "#85CAFF",
        40: "#53B1FD",
        50: "#2E90FA",
        60: "#1470EF",
        70: "#175CD3",
        80: "#1849A9",
        90: "#1A4184",
        95: "#112A56"
    }

};
export const System = {
    light: {
        Primary: {
            primary: Reference.Primary[40],
            primaryContainer: Reference.Primary[10],
            onPrimary: Reference.Base.White,
            onPrimaryContainer: Reference.Primary[70],
            primaryLight: Reference.Primary[30],
            primaryDark: Reference.Primary[50],
            primaryContainerLight: Reference.Primary[6],
            primaryContainerDark: Reference.Primary[20],
        },
        SurfaceContainer: {
            surfaceContainerHighest: Reference.Neutral[30],
            surfaceContainerHigh: Reference.Neutral[20],
            surfaceContainer: Reference.Neutral[10],
            surfaceContainerLow: Reference.Neutral[6],
            surfaceContainerLowest: Reference.Neutral[3],
        },
        Error: {
            error: Reference.Red[50],
            errorContainer: Reference.Red[10],
            onError: Reference.Base.White,
            onErrorContainer: Reference.Red[80],
            errorLight: Reference.Red[40],
            errorHigh: Reference.Red[60],
        },
        Success: {
            success: Reference.Green[50],
            successContainer: Reference.Green[6],
            onSuccess: Reference.Base.White,
            onSuccessContainer: Reference.Green[90],
        },
        OnSurface: {
            onSurfaceVariantLow: Reference.Neutral[40],
            onSurfaceVariant: Reference.Neutral[50],
            onSurfaceVariantHigh: Reference.Neutral[70],
            onSurface: Reference.Neutral[80],
            onSurfaceHigh: Reference.Neutral[90],
        },
        Outline: {
            outline: Reference.Neutral[30],
            outlineVariantHigh: Reference.Neutral[40],
            outlineVariant: Reference.Neutral[20],
        },
        Surface: {
            surfaceBright: Reference.Base.White,
            surface: Reference.Neutral[3],
        },
        Info: {
            info: Reference.Blue[50],
            infoContainer: Reference.Blue[6],
            onInfo: Reference.Base.White,
            onInfoContainer: Reference.Blue[95],
        },
        Inverse: {
            inverseSurface: Reference.Neutral[80],
            inverseOnSurface: Reference.Neutral[3],
        },
    },
    dark: {
        Primary: {
            primary: Reference.Primary[20],
            primaryContainer: Reference.Primary[80],
            onPrimary: Reference.Primary[90],
            onPrimaryContainer: Reference.Primary[10],
            primaryLight: Reference.Primary[10],
            primaryDark: Reference.Primary[30],
            primaryContainerLight: Reference.Primary[70],
            primaryContainerDark: Reference.Primary[90],
        },
        SurfaceContainer: {
            surfaceContainerHighest: Reference.Neutral[50],
            surfaceContainerHigh: Reference.Neutral[70],
            surfaceContainer: Reference.Neutral[75],
            surfaceContainerLow: Reference.Neutral[80],
            surfaceContainerLowest: Reference.Neutral[90],
        },
        Error: {
            error: Reference.Red[10],
            errorContainer: Reference.Red[70],
            onError: Reference.Red[95],
            onErrorContainer: Reference.Red[6],
            errorLight: Reference.Red[6],
            errorHigh: Reference.Red[20],
        },
        Success: {
            success: Reference.Green[40],
            successContainer: Reference.Green[70],
            onSuccess: Reference.Green[90],
            onSuccessContainer: Reference.Green[6],
        },
        OnSurface: {
            onSurfaceVariantLow: Reference.Neutral[60],
            onSurfaceVariant: Reference.Neutral[50],
            onSurfaceVariantHigh: Reference.Neutral[40],
            onSurface: Reference.Neutral[30],
            onSurfaceHigh: Reference.Neutral[20],
        },
        Outline: {
            outline: Reference.Neutral[60],
            outlineVariantHigh: Reference.Neutral[50],
            outlineVariant: Reference.Neutral[70],
        },
        Surface: {
            surfaceBright: Reference.Base.Black,
            surface: Reference.Neutral[95],
        },
        Info: {
            info: Reference.Blue[30],
            infoContainer: Reference.Blue[80],
            onInfo: Reference.Blue[95],
            onInfoContainer: Reference.Blue[3],
        },
        Inverse: {
            inverseSurface: Reference.Neutral[20],
            inverseOnSurface: Reference.Neutral[80],
        },
    }
}